name = "CenteredDifferences"
uuid = "c90fe1c6-2f96-401d-ae77-e500ce532cc4"
authors = ["Louie SLocombe"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
